/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LtcSideDrawer {
        /**
          * The title of the side drawer.
          * @default 'Lorem Prop Defaltum Titulum'
         */
        "title": string;
    }
}
declare global {
    interface HTMLLtcSideDrawerElement extends Components.LtcSideDrawer, HTMLStencilElement {
    }
    var HTMLLtcSideDrawerElement: {
        prototype: HTMLLtcSideDrawerElement;
        new (): HTMLLtcSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "ltc-side-drawer": HTMLLtcSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface LtcSideDrawer {
        /**
          * The title of the side drawer.
          * @default 'Lorem Prop Defaltum Titulum'
         */
        "title"?: string;
    }

    interface LtcSideDrawerAttributes {
        "title": string;
    }

    interface IntrinsicElements {
        "ltc-side-drawer": Omit<LtcSideDrawer, keyof LtcSideDrawerAttributes> & { [K in keyof LtcSideDrawer & keyof LtcSideDrawerAttributes]?: LtcSideDrawer[K] } & { [K in keyof LtcSideDrawer & keyof LtcSideDrawerAttributes as `attr:${K}`]?: LtcSideDrawerAttributes[K] } & { [K in keyof LtcSideDrawer & keyof LtcSideDrawerAttributes as `prop:${K}`]?: LtcSideDrawer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ltc-side-drawer": LocalJSX.IntrinsicElements["ltc-side-drawer"] & JSXBase.HTMLAttributes<HTMLLtcSideDrawerElement>;
        }
    }
}
