/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LtcSideDrawer {
        "exampleMethod": () => Promise<string>;
        /**
          * Defines whether the side drawer is opened or closed.
          * @default false
         */
        "opened": boolean;
        /**
          * The theTitle of the side drawer.
          * @default 'Lorem Prop Defaltum Titulum'
         */
        "theTitle": string;
    }
    interface NasaApod {
    }
}
declare global {
    interface HTMLLtcSideDrawerElement extends Components.LtcSideDrawer, HTMLStencilElement {
    }
    var HTMLLtcSideDrawerElement: {
        prototype: HTMLLtcSideDrawerElement;
        new (): HTMLLtcSideDrawerElement;
    };
    interface HTMLNasaApodElement extends Components.NasaApod, HTMLStencilElement {
    }
    var HTMLNasaApodElement: {
        prototype: HTMLNasaApodElement;
        new (): HTMLNasaApodElement;
    };
    interface HTMLElementTagNameMap {
        "ltc-side-drawer": HTMLLtcSideDrawerElement;
        "nasa-apod": HTMLNasaApodElement;
    }
}
declare namespace LocalJSX {
    interface LtcSideDrawer {
        /**
          * Defines whether the side drawer is opened or closed.
          * @default false
         */
        "opened"?: boolean;
        /**
          * The theTitle of the side drawer.
          * @default 'Lorem Prop Defaltum Titulum'
         */
        "theTitle"?: string;
    }
    interface NasaApod {
    }

    interface LtcSideDrawerAttributes {
        "theTitle": string;
        "opened": boolean;
    }

    interface IntrinsicElements {
        "ltc-side-drawer": Omit<LtcSideDrawer, keyof LtcSideDrawerAttributes> & { [K in keyof LtcSideDrawer & keyof LtcSideDrawerAttributes]?: LtcSideDrawer[K] } & { [K in keyof LtcSideDrawer & keyof LtcSideDrawerAttributes as `attr:${K}`]?: LtcSideDrawerAttributes[K] } & { [K in keyof LtcSideDrawer & keyof LtcSideDrawerAttributes as `prop:${K}`]?: LtcSideDrawer[K] };
        "nasa-apod": NasaApod;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ltc-side-drawer": LocalJSX.IntrinsicElements["ltc-side-drawer"] & JSXBase.HTMLAttributes<HTMLLtcSideDrawerElement>;
            "nasa-apod": LocalJSX.IntrinsicElements["nasa-apod"] & JSXBase.HTMLAttributes<HTMLNasaApodElement>;
        }
    }
}
